<?php

namespace AppBundle\Repository;

/**
 * MailContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailContactRepository extends \Doctrine\ORM\EntityRepository
{
}
