AppBundle\Entity\MailContact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MailContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        message:
            type: text
    lifecycleCallbacks: {  }
